Add swap functionality
svenstaro/wmfocus pull request #325
Opened 2023-12-29 15:18 UTC by Nukesor

Hey,

I added a `swap` flag to swap the currently active window with the selected window.

It's quite handy for multi-monitor setups :)

2023-12-30 13:17 UTC, svenstaro requested changes
Thanks, super neat! Just tiny nits.

2023-12-30 13:17 UTC, svenstaro commented on CHANGELOG.md
> +## [1.5.0] - unreleased
Put this under `[Unreleased]` or my release script won't work. :{

2023-12-30 13:18 UTC, svenstaro commented
Also please fix the lints. )

2023-12-31 17:52 UTC, merged

2023-12-31 17:52 UTC, svenstaro commented
Top nice! 👍

2024-03-01 18:27 UTC, uunnxx commented
It's awesome!
Thank you <3