Feature/exit keys
svenstaro/wmfocus pull request #89
Opened 2021-07-09 22:10 UTC by Rephobia

Hello, thanks for this tool. I use it in my expose script and missprints are annoying. This pull request adds the `--exit-keys` option. The option takes a space separated sequences where each sequence separated by '+', eg `--exit-keys Control_L+g Shift+f`.  Keys pressing don't equal to the option sequences will not cause the tool to exit. If the option isn't passed, behavior is old.

2021-07-10 06:24 UTC, svenstaro requested changes
This is great! I only have small nits apart from the code lines: Could you add back the log lines you removed? I find them quite helpful when debugging the flow of the tool. Aside from that, I'm happy to merge as is. :)

2021-07-10 06:24 UTC, svenstaro commented on src/main.rs
> +                        let kstr = utils::convert_to_string(ksym);
I like how you snuck in this little cleanup.

2021-07-10 10:24 UTC, Rephobia commented
Thanks for the review, i finalized the pull request

2021-07-11 10:50 UTC, merged

2021-07-11 10:51 UTC, svenstaro commented
Good stuff, thanks!